### ISSUE TITLE
typesetting error on cover and title page

### ISSUE THREAD

**Issue by jbullock35** [standardebooks/ford-madox-ford_some-do-not#6]
The book's title is _Some Do Not…_ But on cover and the title page, it's rendered as _Some Do Not …_—that is, with a space between the last word and the ellipsis. The space shouldn't be there. You can verify this point by checking out the HathiTrust scan of the title page from a 1924 printing of the book: https://babel.hathitrust.org/cgi/pt?id=uc1.b4097697&seq=11.

**Comment by acabal** [comment]
That is a hair space, which depending on your font or renderer may be rendered to appear too wide. Typically it renders the same width as the spaces between the dots. It's our house style to include a hair space before all ellipses.

**Comment by jbullock35** [comment]
Thank you. I do see that a hair space is used for rendering in some way. But in three very different .epub readers — Calibre 7.23, Adobe Digital Editions 4.5.6, and Google Play — the cover and title page are rendered inappropriately, with a full space before the ellipsis. This makes me think that the problem is general. 

Here are screenshots from Calibre that illustrate the issue:

> ![image](https://github.com/user-attachments/assets/28ea1b1f-5682-420c-9546-8b4517725b55)
> ![image](https://github.com/user-attachments/assets/d7764477-a2d3-4e4b-9b14-3ff2f13afebd)

Possibly related: https://github.com/standardebooks/ford-madox-ford_some-do-not/blob/master/src/epub/images/titlepage.svg shows a large space, not a hair space, before the ellipsis. At least on the Windows versions of Chrome and Firefox.

If the problem is simply that all of these browsers and .epub readers have faulty rendering, is there a reader or renderer that you recommend?

**Comment by acabal** [comment]
Those images are rendered with the League Spartan font which probably does not have a good hair space character. Unfortunately not much we can do about that at the moment. Sorry!
